# on 2014-05-05 19:41:29 +0200 using RuboCop version 0.18.1.
# The point is for the user to remove these configuration records
# one by one as the offences are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offence count: 39
Documentation:
  Enabled: false

# Offence count: 7
EmptyLinesAroundAccessModifier:
  Enabled: false

# Offence count: 1
# Cop supports --auto-correct.
EmptyLinesAroundBody:
  Enabled: false

# Offence count: 2
IndentationConsistency:
  Enabled: false

# Offence count: 88
LineLength:
  Max: 154

# Offence count: 1
# Configuration parameters: CountComments.
MethodLength:
  Max: 14

# Offence count: 2
# Cop supports --auto-correct.
NumericLiterals:
  MinDigits: 7

# Offence count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
SpaceInsideHashLiteralBraces:
  Enabled: false

# Offence count: 92
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
StringLiterals:
  Enabled: false
