language: ruby
rvm:
- 2.0.0
before_script: bundle exec rake db:drop db:create db:migrate
script: bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: hMq1wJldCR6b7bikxqa1IvYzn6P2/epzWPqDNakxYh4QMlgp+GmJpKuDW8e5j6DDZLbV8oAWB24cN3lVAMYZjP3hjO4fDbHerkS6/wIqp8Kdfnohb26ey/5i/Epp8owalW4PgvUNerKIFDm541KItxs0rqyx2hR6olLDoQ61AUk=
  app: qapi
  on:
    repo: secretBears/QAPI
  run: rake db:migrate
env:
  global:
  - secure: W4stQ46IZEyew/rX4SdMy+krNEfP/zcCqxrbrP4wVm84gmJZSpW+iKHD2J/7JFzN5ErqoGTvox0TLy7sCnVFHAwdsuUEegpkBS3RKQw7jtXHxmq9wpZxu034fFt3DB61LiGNwDuyZ0lnGJbCMiXHrZzCJKS/ckBRQub12IKpPRc=
  - secure: C0YVtDqMag4bxCYzjq3DwfITCz6fc2I4tycenjesBvr6u6D49dLYJzLDZhsn0atlwgmXMYkh0p695An0eDQqPJXsKVcTjyADqVsZqd3GnTZpBLEFyrWUgYkpusvxRj0hrP0t68BW+DeZW4zJ414LlvcYwHiPG3O2j/V2ScOHyu4=
  - secure: BQ7enD3q+5x/bHDCdeGzrGsf/6Re12JYH0UCvSeSOag+EtP2ga5Vbl/54EDmU/hwEV8W8XugnOz6rHyl3i1xdbOChhsn85l7vmWsRgUu7Mr1mIM10NxIbnYFXfF+ZE0mSRdO98CGZAPaCn9hofQFuytTKTIp57iuH32sIvNMbqQ=
  - secure: wbNuJhFRTw4V1f0gVo3iG9QCgzJPa4UnmNxyl7dxhOHAgKQDLw3KahNR9IYDvxL5QhR6cnfdgpwe56k9TdVj2lagSQFeSAcnKDocXpNrZ8TkIRYTW6IMLkzD13Z/AXfUAHaj8u0hFUZbENrP6kN59g31hHDss7YeFrtGC7BD9is=
