language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- export DISPLAY=:0.0
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
env:
  global:
  - secure: CQkmyMUDFQ9SW4zUuGF/Woy9F2KiOdF1yfO134i7SWtUjfbLSbj6jjMcB3wya/2+oJMnh0q9H+iARTKCCDl2vOWnnePa3RFnGAPPQUB37/Ii+erq/ChbJrYdIuppNGsMlATPdsM8mLBx5j7UidW2gbJA7S2JuQFXiPkY3dUPggY=
  - secure: VBGBM9LzCfopewoYqnuo8CgHgntqUFo3R3WKPgjFU330JPDcuHjHvEXc0jITgM4QVT3PlDpSL9oBsnFiLQdQajPnuUScJjq4Yhv+vZ1SUg+WDR4aGlMBfsetsKRwpvVH4VGbiQZ/Ch9tdSPOgOFVET+9Ag+foLbsSPChBy+d7W8=
  - secure: RtXNcYwY4YBomtxc5ssJIcuBUgpX1RUxk3GLBkf50vk55d/MYiT0iM2LHygyLZ23MY0Db9UPzHyeIG/M8GMPKFENUwSuCJY/xEDaWEU+HDvWbEyo/g0EkRI/SyuihwrGgWX71ZIlMiMV45pJB4uyEI3VSS1fc22GBvzEafe6yeY=
  - secure: H4cRi0/y7GKwp+5BUjxKACajqqeQ7dSvxRbxxJ19QTjove9G02JEhKopjFfXlZOluYEUPnbCQ9jLi4JQ3ER8Zo1JkjWLNjMnTB9+8kCRBSEBHoqC6tPnCPHWT5nZfv+YLvulvGQH3TjjAg+SgCqm7OHzEW6fhtc61/F7dWY07+g=
  - secure: F+3Xi5uQVX7yg63kzh6qZLIkZd42H0e0ez6Oj6P1J3qYy5kz2bE4q2n6pGSkBKguRBCGGNpTr/GFs+0x9GgRIHNdAPhg5VN7nx3WVrMLA3UbZRwhUwivgmCfN7zyKhwABPHTZxBEH63kgib7Y2rhZcTCcAfoxO2sLr2WiGl6T9Q=
deploy:
  provider: heroku
  api_key:
    secure: EqR6M+iws60nQJ0a0QgwVfHJhVVmJ6NRgtp9tqEdiBprbSPQSvV2uTgGw4U/jcDWAAhc46WHyj5NF3Gtmc9+AnKUW2lbHVOdyuDcbFA96ZSkE5rhFZecVxY7vdutGNUKca5pC+GhJK80DdoBDlGWjKTIATsfGpSx4V6QLocVkP8=
  app: qapi
  on:
    repo: secretBears/QAPI
