language: ruby
rvm:
- 2.0.0
before_script: bundle exec rake db:drop db:create db:migrate
script: bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: hMq1wJldCR6b7bikxqa1IvYzn6P2/epzWPqDNakxYh4QMlgp+GmJpKuDW8e5j6DDZLbV8oAWB24cN3lVAMYZjP3hjO4fDbHerkS6/wIqp8Kdfnohb26ey/5i/Epp8owalW4PgvUNerKIFDm541KItxs0rqyx2hR6olLDoQ61AUk=
  app: qapi
  on:
    repo: secretBears/QAPI
