language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- export DISPLAY=:0.0
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
env:
  global:
  - secure: anZHhLi0ysEF1b8S4H5Xxy6yKsHAj0TFOMJDw4bmVK2/18HAn7+WcM/6rH7a5J6tml1zhRpJL2gbDwZOCOI1cW/H+w5UP/uQ6kxfuGY9xhYgVO684mNSEoFLwLppldkvRuB1h59A+yhAd9aesFZC+b36sJEBqXLF086APc/9Jq4=
  - secure: VC/5adrnR9Ht48NPdfmxsC5xHNC0OlXqsD0pIP3SDWT6FoOZWnrmxi3dhZlcTyrRonLr4ytiMW33zuhv6oOG0XV0sKJspxihCuwwBYAYawzy3kPEKbAOEZYAp//2GNHCRPd4f8ixv/T3uSuRwA1c6NjWiTH1U8fX84qv9W8jcuU=
  - secure: ixxG71E2Wlj9bYgHNBpXyvYJYilNxHtQAsw5lSjqFf7u4JKkVAo/dNIxoDertG18w30UcRZtUH2+sfv2Y4BJTupQ3MlCAeDNTKucY1RlYFACIFzpS9A9fWkzXKZb6ywAomEVX1g/PbEXM7XITdx7eAe2BBWrzyPockgaGgBc9rE=
  - secure: QPwj/UVhk3QLa3nBgMW1EyO1Yphose+GEAmFPX3Tu3KNTtiZWxP8zTkIt4sp/yrwwtDggiltJXyLdQv33OdUEVL6Jw57dxqWFHUuaBteEPgD2LG2+RY67TjjPW+oTr/6/Z0/4vtLlU0IFsWUg8HCFms86Kt9Pi2XEAwzBeMTUkQ=
  - secure: IkUsRYx+PHVCKQ6hvTr10/RDfuUc4fDUi9IACI8mpnjPsM8XBD1GYl+5Oj6NFklV/T8143f0Opc52r6KAxTa3bbcD8MR496o43PNhJXYc22F0rsP/zGpDPHs61oCbciqdS2nckXZh6J6xG0wHMQaVPOlEto26+sejivZT46C/ug=
  - secure: BfmvrLX8vlVoGILk+PNYWeWXWAk12jl+qtaXc6jqkKpS7207HvClNp4lkWzb+h0Qd3/FP3Nf2ZcHcPkZ6jz07+xxNPP0UIYqnW2PDGjPLglyD4VOANFwC7W5AqF9anokNYhZ0u5IdHbOjo3zfz+7P+jSAbH0CDeVtSpQnpsEQBk=
deploy:
  provider: heroku
  api_key:
    secure: oOSEuqxOSA5LH7JGXxefGbaQDnFiujaZ3S0x+9rSQrI18ihOVzbkdoGDKFY+Y946mXBXS7HVWMZwbDT153IMChKQZ6jp1N0qEbSlzisU9AfJXCCeCfkcNuo/xnnPaO1g2/vuw+H8wb3Hjl3htkpRAeFaSYMCThh4XJ39xMBxlNY=
  app: qapi
  on: master