language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
env:
  global:
  - secure: qFX0GSasjCbJDrBqTPeRzeq3SqSiLo9ecoXJhxZ3qs4DUCBIwJO7wUPYlBKk3CGXUVnhVCJCHCf2evj1tzmOsG78siVAePsPflZRtaowSiH+QEpsYRSzJvyMxrZV3z/Sl1YTdKnCkimRkuZGOCD3GYkT+xwnQFGGMHhGVc+jUX8=
  - secure: qgnKh6vyt1Xfkpw6wi+LY5lTYd7u8cDiJlOLBTYedIXiRypiadaQ3u0NCje54hdCi1GnhlgY2g6Fk5k8ailrPpid0LIWp1TboAOTC1LMbP644BAeCEkCoIXV6mP5WMMYNa8sU3uttEKMsGQ+mvqNvAlgE4mCFfOKl1zb5J0AsMU=
  - secure: fBjytIiE9jrCOODvn+LZ4M2eye7m+8uxeeAIddG5iHWimJKetUOwcMp1HclKKrlxG59oHn5w4BO9T5zdntnZck129iRbsxtykiYFqA03pvL2yeTaIjBlSPaFsaHQdl4iIOFnTvD6P+GUwvjiwwFS0q6QCAv8PjQzqlvIgXemXSM=
  - secure: jYBAqSO89FPOJ6CeQboxUzj8d9fMlhGBW2A8C+j4/GU/pBHk34ueqacX+vvy3gofMnRKF086zIqfICJPbjY/0ayB922cxrkM9NXRNEVQx7TH/OM2VyjbLKqnDO2nxXbTOx2NrjW69Ca3Rbjb+L7CR1QM5A21cInhq7bMxa02HkU=
deploy:
  provider: heroku
  api_key:
    secure: atRxuL4Qls6E1PG+gZwTFZkcfBje/d4eLYZ1UmZc8Z0YkdyqeDSx4kF3syNGq9V8TlAzr6JFvxXizD1Axd4t7PhoQUwaYppXJxYUCgd6iH/iLu/PiY+EB1cE3St7OQ8XvToDdxNkDfYqsDPuTy1enU2FNL8mKsiF2JF+7kPmiN0=
  app: qapi
  on:
    repo: secretBears/QAPI
