language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
after_script:
- rake assets:precompile
env:
  global:
  - secure: ewt0H2XynJ7mK/fOiHQgr9j6Qc8FMtrf00qqspSaYQKjuHwEK7h80qv8Ov1IZl1Gkq3TOgUNX5EVspEjCzEDAuPIgsN7dbTDlkm3Gfddo8OTD34d+PINR9zdauPtuoA9f68bmfxMYoQn0RXZrIBcpwcezGy59bQVyYLq82Yi/m0=
  - secure: iMj5Nu/SWYSfNZLpoW1Guw2rQSVLVczRfjn/sLQs3PQMKUDxOQLeyywx9zjzaWuRWt3wxeRBSHal9MVGuDJBqSvodQiAloo3MBjwbXCnWDkapHoLt8YMmRyAWTLfhBSbhKXh8SJcghl+5Ts0elvvNQwFmgHNrnTmR62RhIDAeYM=
  - secure: T1WUuEdZMkn/yLNXSadHttU3pIhZs58Kx9r5FMaaMPwe95xktMW5xCo3l8siEWQaX4j3CCJNhVEHkqHSm30PHayUEgGx9sgPGUt+T7k7skLctSLb895BYbqAF1FlwltsDKgRRJFHS33yy0ksU1TFdY9dHr5+YRz7uL40ZkZrubM=
  - secure: gr1LASYbQwwNXc11qmdQYVRBPrq3kn2IAbFgplttKkqqqId2pImy1zSb+kx5j1iaurJQjIcE463pphsncCRH2WkdsMQJFkJ/A0PBysGzLxiALrpk0Vg+ymHwSUFSwtyfHyyWakDEVpFFdka3Z4z2MIEgnFPfRbeNBXSayB2YJNo=
  - secure: fF/UR+kixc9bgbEn6XM3+raKKrfWlzgMcL5s/zjtBxB/jw54Z3wFIJunb/2MZoG7cvwDEH1bQT9ky7SAhh7p+rOAo+8vbdibb9HKWSx8VX2Rn5uulBWjchEjrnw50O6UIl2Oj/f7t+eZWzyqvnsUEIKbhn0uNQ/D+rLs7sifyWQ=
deploy:
  provider: heroku
  api_key:
    secure: atRxuL4Qls6E1PG+gZwTFZkcfBje/d4eLYZ1UmZc8Z0YkdyqeDSx4kF3syNGq9V8TlAzr6JFvxXizD1Axd4t7PhoQUwaYppXJxYUCgd6iH/iLu/PiY+EB1cE3St7OQ8XvToDdxNkDfYqsDPuTy1enU2FNL8mKsiF2JF+7kPmiN0=
  app: qapi
  on:
    repo: secretBears/QAPI
