language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- export DISPLAY=:0.0
- bundle install
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
script: bundle exec rake test
env:
  global:
  - secure: YPm67vFPh6c5hdf0kGcw0NzUMnJOF6RmmNFHl1prvOW4NKqrWezwvQjfF89M4uHH5caMLN6gP2x/TqW0cLDANaf41Gb4gq76bqSVY8Lo0BY3I4EwW49jFsZya6BQFO0KV0K0GfN+/+QDMDiVO2q8Ft8KSXOxSGs5NRTnzvJeELI=
  - secure: LDqSiBXzBeR9BHpIg2YUy1Zz47rtLAZaXSXSJY0NIyvloXCI871ile0CByfR0wvgwr5JdMXuPPOmpT/MGOqEvAEq/zdhWihY201MLN8lC3jbKeIXZ1rt7hvo1qCGYg+Beoc9RtUVbIvLzaOb6TtekK0oFvYnO5Rkmyp9kX6+Nvw=
  - secure: MHHD7h8GLSOk/LkKyzV542KrQi6NxAjIPeJ9EfWRUekvtKnwTxOdlSAzPAg3lFPB2BxzCh9IhFKoLqg2mpR4qmBHFgStdRu/S9ker8x5xjWlP2+FHwHPDTsCRkSf5IC06o/gD8kBDjjmwtw+LelwDQJNCiaSGIRnZw0RYgCRY6A=
  - secure: EdBkyn0Q18ccXKn4vQED9Uf2waOEOiV3PsoaxQY2lUTNoQiZOWJv3Q5AKsXCIHpKq7+406BA4hZBy7epG4SuE5HxJacHdlq5rxsfjoTqZPZQfa0xaGNP8s/ZN0fy7gI7S+bVtPmwutM62Cv7Cc2TIL3VnN+RzWRGnewXBz7bKUc=
  - secure: DANpCYI3tNIV3+5oV9x5p3IU+eMotnGRiTLp1vDxEBUqZOtno18Oyo3Oo/JxiqGabzg2Fu1V9sBgdt+o7IKa/wItDZa9nFbd5bhDRnzgaD6El+UbnoyC8RkQRK4saGeT7pq28rC7NpBwai6OP8LPpdNJYAO56+wqFHNPpTquSqs=
  - secure: Wz/xFbxCsJwrslFSIqKZr8KxxmzPABsi7uZTYSU4csd4HgDEzprFfRKfHYfmoCkfNpQiHnYWjsEqTr1spat/sDwLUDhJW8c2vRNEqx1DDv61bhiJE9Tn5FU9BkNyYEOAqd4mO5eUNrjUr+ppCd92Nlh8WN+WzVf1UaxOXxegiWI=
  - secure: U2CijpBr0kguHwyLp2nCIt/RJRU/wjcYU2NipfJWdUwhwquG7TkG9etI+4D/RHjOopmv2P/v95k35lp85IQfxcGCrMder8ICqVAy4TfkMJP0+FO+J2kxHenBcFMR8AVhTqpD7O9csPK29hX52l378VwTcEzSzYBr6UyrCKW11Og=
deploy:
  provider: heroku
  api_key:
    secure: oOSEuqxOSA5LH7JGXxefGbaQDnFiujaZ3S0x+9rSQrI18ihOVzbkdoGDKFY+Y946mXBXS7HVWMZwbDT153IMChKQZ6jp1N0qEbSlzisU9AfJXCCeCfkcNuo/xnnPaO1g2/vuw+H8wb3Hjl3htkpRAeFaSYMCThh4XJ39xMBxlNY=
  app: qapi
  on: master
  run:
  - rake db:migrate
  - rake precompile:assets
