---
language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- cp config/database.yml.travis config/database.yml
- bundle exec rake db:setup
- bundle exec rake travis:setup
script: bundle exec rake test
env:
  global: []
deploy:
  provider: heroku
  api_key:
    secure: atRxuL4Qls6E1PG+gZwTFZkcfBje/d4eLYZ1UmZc8Z0YkdyqeDSx4kF3syNGq9V8TlAzr6JFvxXizD1Axd4t7PhoQUwaYppXJxYUCgd6iH/iLu/PiY+EB1cE3St7OQ8XvToDdxNkDfYqsDPuTy1enU2FNL8mKsiF2JF+7kPmiN0=
  app: qapi
  true:
    repo: secretBears/QAPI
