language: ruby
addons:
  postgresql: '9.3'
rvm:
- 2.1.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database qapi_test;' -U postgres
- rake db:setup
script: bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: hMq1wJldCR6b7bikxqa1IvYzn6P2/epzWPqDNakxYh4QMlgp+GmJpKuDW8e5j6DDZLbV8oAWB24cN3lVAMYZjP3hjO4fDbHerkS6/wIqp8Kdfnohb26ey/5i/Epp8owalW4PgvUNerKIFDm541KItxs0rqyx2hR6olLDoQ61AUk=
  app: qapi
  on:
    repo: secretBears/QAPI
  run: rake db:migrate
env:
  global:
  - secure: KDVcW3ru0S0q1eOOT2AgNcdfcbt6fGiuIyh8Gl2PJOd5wbnfgAnKMxfjety4+YssJ5Dlk0y9ZMpKF80m0oxeM6e6rVws0jmA6oM7tApMnS5XNs2P40MsqplNWkGfhRsmmXmwTX7BTB305ur1Urr16yXOkt4FrDMYH1cjdj53muI=
  - secure: Gtb4SMnIeVCRzE7Bg14IVfTElrkTcLZjooi0DvN8oREbxfaSl3WLm7/F9V2hwPfw2FN8O1UPSY0NIap5YnE3QNPb6YKnME0EXn4KMxD0u8L629l94XFYlL8wJTZTV65qtAkXm3aLc//Pu4PfsSP504NkcFQH59fzYo9ALhFYRLs=
  - secure: hWOtjyQGwxFmSdMfpr5/Nz2aT683F/23c12IAHuNxYF17ydDX2HsuxOvidMwIW92p0wxrg6UXiBmRrc2ZM1ycUk0WxF7HTOHX3DwkXuPPb8RttGYHnsNOd1U41npNoNT6MveMWXGUscNKl3w52NzvAHK5NmhyD9nl+D0iHW9fOM=
  - secure: EC/VMK6kyh+YuyE6CleRYkOFfT/tF5yvJ3RKwi1ldV2cr214i9BDhlbzg/6v6EvuiO6jabIUSqBU4xEphSJyJA8t3ZZZbKg0uFXxghmXalxaL834nGdEI+Su+B+G6iH+OLHvP3z8uvVhoMMhajF5ntmGuiWTZcJRhbCV8imawgU=
