# Add application configuration variables here, as shown below.

SECRET_TOKEN: 'secret token'

GOOGLE_CLIENT_ID: 'place google client id'
GOOGLE_CLIENT_MAIL: 'place google client mail'
GOOGLE_API_KEY: 'place google api key'